### ISSUE TITLE
Getting an error message when using the command ./warp.sh

### ISSUE THREAD

**Issue by oliviagwallace** [jonnyhuck/EnRoot#1]
Hello, 

First off - thank you for providing this awesome resource. I have been following the how-to-use guide from the article by Dr. Arnaud about the EnRoot minirhizotron. However, I run into an issue when I run the command ./warp.sh and get the following error message:

ERROR 1: The transformation is already "north up" or a transformation between pixel/line and georeferenced coordinates cannot be computed for tmp.vrt. There is no affine transformation and no GCPs. Specify transformation option SRC_METHOD=NO_GEOTRANSFORM to bypass this check. 

Any ideas on why this is occurring or how to fix it?

**Comment by jonnyhuck** [comment]
Hi Olivia,

OK, it looks like GDAL can't see your GCP file, so two possibilities spring to mind:

1. Have you definitely created your `pointsfile.points` file using QGIS, and put it in the EnRoot directory?

2. Are you running Python 3? It might be that the bundled Python code is for Python 2 and you have Python 3, which means it won't work which would prevent GDAL from being able to read the points file, which might lead to the same error.

I will get it updated to Python 3 (a very minor job), but if you have your points file then the issue could well be 2, so using Python2 would be. Good quick fix

If neither of the above is any use, can you send me your points file, calibration image and an image that you want to warp and I can take a look?

**Comment by jonnyhuck** [comment]
Hi Olivia,

From a test this morning it seems likely that the issue was that the `points2gcp` code was written for Python2, rather than Python3 - I have just pushed an updatre, so it should work fine for you now. 

Has that solved it?

**Comment by oliviagwallace** [comment]
Yes, that was the issue! Thank you so much for your help.
